// <auto-generated />
using System;
using BPLM.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BPLM.Domain.Migrations
{
    [DbContext(typeof(BPLMDbContext))]
    partial class BPLMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BPLM")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BPLM.Domain.Entities.Lesson", b =>
                {
                    b.Property<string>("LessonID")
                        .HasColumnType("text")
                        .HasColumnName("lesson_id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("DurationMin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duration_min");

                    b.Property<bool>("IsExam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exam");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Student")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student");

                    b.Property<string>("TutorID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tutor_id");

                    b.HasKey("LessonID");

                    b.HasIndex("TutorID");

                    b.ToTable("Lessons", "BPLM");
                });

            modelBuilder.Entity("BPLM.Domain.Entities.Tutor", b =>
                {
                    b.Property<string>("TutorId")
                        .HasColumnType("text")
                        .HasColumnName("tutor_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("TutorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tutor_name");

                    b.HasKey("TutorId");

                    b.ToTable("Tutors", "BPLM");
                });

            modelBuilder.Entity("BPLM.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("BPLM.Domain.Entities.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
